name: Deploy Starwars API App

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install modules
        run: npm install
      - name: Build dist
        run: npm run build
      - name: Setup pages
        uses: actions/configure-pages@v5
      - name: Upload dist folder
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build'
      - name: Deploy to GitHub pages
        id: deploy
        uses: actions/deploy-pages@v4
